import type { Timestamp } from 'firebase/firestore';

export type Priority = 'low' | 'medium' | 'high';

/** users/{uid}/semesters/{semesterId} */
export type Semester = {
  id: string;
  name: string;
  year: number;
  term: string;
  isCurrent: boolean;
  gpaTarget?: number | null;
  /** Manual ordering; lower sorts first. */
  order: number;
  createdAt: Timestamp | null;
};

export const TERMS = ['Semester 1', 'Semester 2', 'Summer', 'Winter'] as const;

/**
 * 4.0-scale grade points. Kept here rather than in the UI so the planner and
 * the calculator can never disagree about what a B+ is worth.
 */
export const GRADE_POINTS: Record<string, number> = {
  'A+': 4.0,
  A: 4.0,
  'A-': 3.7,
  'B+': 3.3,
  B: 3.0,
  'B-': 2.7,
  'C+': 2.3,
  C: 2.0,
  'C-': 1.7,
  'D+': 1.3,
  D: 1.0,
  F: 0.0,
};

export const GRADE_OPTIONS = Object.keys(GRADE_POINTS);

/**
 * Credit-weighted mean, ignoring subjects with no grade recorded yet.
 *
 * Both fields are required rather than optional: with `creditHours?` a caller
 * whose rows name the field something else stays structurally assignable and
 * silently gets a GPA of null over zero credits.
 */
export function calculateGpa(
  entries: { creditHours: number | null | undefined; grade: string | null | undefined }[]
): { gpa: number | null; credits: number; graded: number } {
  let points = 0;
  let credits = 0;
  let graded = 0;

  for (const entry of entries) {
    const weight = entry.creditHours ?? 0;
    credits += weight;
    const grade = entry.grade ?? '';
    if (!(grade in GRADE_POINTS) || weight <= 0) continue;
    points += GRADE_POINTS[grade] * weight;
    graded += weight;
  }

  return { gpa: graded > 0 ? points / graded : null, credits, graded };
}

/** users/{uid}/subjects/{subjectId} */
export type Subject = {
  id: string;
  name: string;
  moduleCode: string | null;
  color: string;
  documentCount: number;
  /** Which semester this subject belongs to; null until the planner assigns it. */
  semesterId: string | null;
  creditHours: number;
  /** Recorded grade, keyed into GRADE_POINTS. */
  grade: string | null;
  createdAt: Timestamp | null;
  updatedAt: Timestamp | null;
};

/** users/{uid}/subjects/{subjectId}/documents/{documentId} */
export type SourceDocument = {
  id: string;
  title: string;
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  /** Full extracted text. Passed wholesale into Gemini's long context window. */
  rawText: string;
  charCount: number;
  /** R2 object key: users/{userId}/{subjectId}/{fileName} */
  r2FileKey: string;
  /** Public or presigned viewing URL for the original file. */
  r2FileUrl: string;
  moduleCode: string | null;
  summary: string | null;
  /** Publication-grade Markdown notes generated by aiNotes. */
  notes: string | null;
  notesGeneratedAt: Timestamp | null;
  /** How the text was obtained — parsing locally, or Gemini OCR/transcription. */
  sourceKind: FileKind;
  status: 'ready' | 'parsing' | 'failed';
  error?: string | null;
  createdAt: Timestamp | null;
};

/** What the file is, which decides how its text is extracted. */
export type FileKind = 'pdf' | 'docx' | 'pptx' | 'text' | 'image' | 'audio' | 'video';

/** users/{uid}/subjects/{subjectId}/chats/{chatId} */
export type ChatSession = {
  id: string;
  title: string;
  /** Scopes the chat to one document; null means the whole subject. */
  documentId: string | null;
  messageCount: number;
  createdAt: Timestamp | null;
  updatedAt: Timestamp | null;
};

/** users/{uid}/subjects/{subjectId}/chats/{chatId}/messages/{messageId} */
export type ChatRecord = {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  createdAt: Timestamp | null;
};

/** users/{uid}/todos/{todoId} */
export type SubTask = {
  id: string;
  title: string;
  isCompleted: boolean;
};

export type Todo = {
  id: string;
  title: string;
  dueDate: Timestamp | null;
  isCompleted: boolean;
  subjectId: string | null;
  subjectName: string | null;
  priority: Priority;
  subTasks: SubTask[];
  /** Set when the deadline was auto-extracted from an uploaded syllabus. */
  source: 'manual' | 'syllabus';
  sourceDocumentId: string | null;
  createdAt: Timestamp | null;
  completedAt: Timestamp | null;
};

/** users/{uid}/weak_concepts/{conceptId} */
export type WeakConcept = {
  id: string;
  subjectId: string;
  subjectName: string | null;
  concept: string;
  question: string;
  correctAnswer: string;
  explanation: string | null;
  timesMissed: number;
  timesReviewed: number;
  /** Leitner box: 0 = new/failed, higher = longer interval. */
  box: number;
  lastMissedAt: Timestamp | null;
  nextReviewAt: Timestamp | null;
};

/** What Gemini returns when we analyse a freshly uploaded document. */
export type ExtractedDeadline = {
  title: string;
  /** ISO YYYY-MM-DD. */
  dueDate: string | null;
  /** 24-hour HH:MM when the source states one. */
  dueTime: string | null;
  /** assignment | exam | quiz | lab | project | reading | presentation | other */
  kind: string | null;
};

export type ExtractedMetadata = {
  moduleCode: string | null;
  subjectName: string | null;
  summary: string | null;
  deadlines: ExtractedDeadline[];
};

export type QuizQuestion = {
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
  concept?: string;
};

export type ChatMessage = {
  id: string;
  role: 'user' | 'model';
  text: string;
  pending?: boolean;
  error?: boolean;
};

export type PodcastLine = {
  speaker: string;
  text: string;
};

/** Deterministic palette so a subject keeps the same colour across devices. */
const SUBJECT_COLORS = ['#B4552D', '#2E6F5E', '#B4832A', '#4C5FA8', '#8A4B86', '#B0443E'];

export function colorForSubject(seed: string): string {
  let hash = 0;
  for (let i = 0; i < seed.length; i += 1) {
    hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  }
  return SUBJECT_COLORS[hash % SUBJECT_COLORS.length];
}
