/**
 * Bindings this Worker uses that are not in the generated types.
 *
 * `worker-configuration.d.ts` is regenerated by `wrangler types` from
 * wrangler.toml, so anything added there by hand is lost on the next run.
 * These three are declared separately because they are all optional: the Drive
 * routes check for them at runtime and answer 501 when they are missing, which
 * is how a deployment without a Google client secret keeps working.
 */
interface Env {
  /** OAuth 2.0 web client id. Public — it also ships in the app bundle. */
  GOOGLE_CLIENT_ID: string;
  /**
   * The confidential half. Set with `wrangler secret put`, never in [vars]:
   * this is the only thing that makes a refresh token possible, and the only
   * reason it is safe to hold one.
   */
  GOOGLE_CLIENT_SECRET: string;
  /** Refresh tokens, keyed by Firebase uid. */
  DRIVE_TOKENS: KVNamespace;
  /** Small, bounded queue for installed-PWA background reminders. */
  REMINDERS_DB: D1Database;
  /** Public half is also embedded in the client bundle. */
  VAPID_PUBLIC_KEY: string;
  /** Set only with `wrangler secret put`. */
  VAPID_PRIVATE_KEY: string;
  VAPID_SUBJECT: string;
}
