import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Button, Notice } from './ui';
import { generatePodcast } from '@/lib/ai';
import { PodcastPlayer, pickVoices, type VoicePair } from '@/lib/speech';
import type { PodcastLine } from '@/lib/schema';

type Status = 'idle' | 'generating' | 'ready' | 'playing' | 'paused';

/**
 * NotebookLM-style Audio Overview: Gemini writes a two-speaker discussion of the
 * sources, then the device's own speech synthesiser performs it with a
 * different voice per speaker. No audio ever leaves the device.
 */
export function AudioOverview({
  context,
  subjectName,
}: {
  context: string;
  subjectName: string;
}) {
  const [status, setStatus] = useState<Status>('idle');
  const [lines, setLines] = useState<PodcastLine[]>([]);
  const [current, setCurrent] = useState(0);
  const [voices, setVoices] = useState<VoicePair | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(false);

  const playerRef = useRef<PodcastPlayer>(new PodcastPlayer());

  // Stop speaking if the student navigates away mid-episode.
  useEffect(() => {
    const player = playerRef.current;
    return () => player.stop();
  }, []);

  const speakers = useMemo(() => {
    const seen: string[] = [];
    for (const line of lines) if (!seen.includes(line.speaker)) seen.push(line.speaker);
    return seen;
  }, [lines]);

  const start = useCallback(
    (script: PodcastLine[], voicePair: VoicePair, from = 0) => {
      playerRef.current.configure(script, voicePair, {
        onLine: setCurrent,
        onDone: () => setStatus('ready'),
        onError: (message) => {
          setError(message);
          setStatus('ready');
        },
      });
      playerRef.current.play(from);
      setStatus('playing');
    },
    []
  );

  const generate = useCallback(async () => {
    setError(null);
    setStatus('generating');
    try {
      const [script, voicePair] = await Promise.all([generatePodcast(context), pickVoices()]);
      setLines(script);
      setVoices(voicePair);
      setCurrent(0);
      start(script, voicePair);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught));
      setStatus('idle');
    }
  }, [context, start]);

  function toggle() {
    if (status === 'playing') {
      playerRef.current.pause();
      setStatus('paused');
    } else if (status === 'paused') {
      playerRef.current.resume();
      setStatus('playing');
    } else if (voices) {
      start(lines, voices, current);
    }
  }

  function stop() {
    playerRef.current.stop();
    setCurrent(0);
    setStatus('ready');
  }

  if (status === 'idle') {
    return (
      <View className="gap-3 rounded-2xl border border-line bg-surface p-5">
        <View className="flex-row items-start gap-3">
          <View className="h-9 w-9 items-center justify-center rounded-lg bg-pine-soft">
            <Feather name="headphones" size={16} color="#2E6F5E" />
          </View>
          <View className="flex-1 gap-1">
            <Text className="text-[15px] font-semibold text-ink">Audio Overview</Text>
            <Text className="text-sm leading-5 text-muted">
              Two hosts talk through {subjectName} using only your sources. Generated by Gemini,
              spoken by your device.
            </Text>
          </View>
        </View>

        {error ? <Notice title="Could not generate the overview" body={error} /> : null}

        <Button
          label="Generate Audio Summary"
          icon="headphones"
          variant="secondary"
          size="sm"
          onPress={() => void generate()}
          className="self-start"
        />
      </View>
    );
  }

  if (status === 'generating') {
    return (
      <View className="flex-row items-center gap-3 rounded-2xl border border-line bg-surface p-5">
        <Feather name="loader" size={16} color="#2E6F5E" />
        <Text className="flex-1 text-sm text-muted">
          Writing a two-speaker discussion of your sources…
        </Text>
      </View>
    );
  }

  const progress = lines.length ? (current + 1) / lines.length : 0;

  return (
    <View className="gap-4 rounded-2xl border border-line bg-surface p-5">
      <View className="flex-row items-center gap-3">
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={status === 'playing' ? 'Pause' : 'Play'}
          onPress={toggle}
          className="h-11 w-11 items-center justify-center rounded-full bg-ink"
        >
          <Feather name={status === 'playing' ? 'pause' : 'play'} size={17} color="#F7F5EE" />
        </Pressable>

        <View className="flex-1 gap-1">
          <Text className="text-[15px] font-semibold text-ink">Audio Overview</Text>
          <Text className="text-xs text-muted">
            {current + 1} of {lines.length} ·{' '}
            {speakers.map((speaker, index) => `${speaker} (${voices?.labels[index] ?? 'device voice'})`).join(' & ')}
          </Text>
        </View>

        <Pressable
          accessibilityLabel="Stop"
          onPress={stop}
          className="h-9 w-9 items-center justify-center rounded-lg"
        >
          <Feather name="square" size={14} color="#6F6A5F" />
        </Pressable>
        <Pressable
          accessibilityLabel={expanded ? 'Hide transcript' : 'Show transcript'}
          onPress={() => setExpanded((value) => !value)}
          className="h-9 w-9 items-center justify-center rounded-lg"
        >
          <Feather name={expanded ? 'chevron-up' : 'chevron-down'} size={16} color="#6F6A5F" />
        </Pressable>
      </View>

      {/* In-flow track: width is a percentage of its own parent, never absolute. */}
      <View className="h-1 w-full overflow-hidden rounded-full bg-sand">
        <View className="h-full rounded-full bg-pine" style={{ width: `${progress * 100}%` }} />
      </View>

      {error ? <Notice tone="amber" title="Playback issue" body={error} /> : null}

      {expanded ? (
        <ScrollView className="max-h-80" nestedScrollEnabled>
          <View className="gap-3 pt-1">
            {lines.map((line, index) => {
              const active = index === current;
              return (
                <Pressable
                  key={index}
                  onPress={() => voices && start(lines, voices, index)}
                  className={`gap-1 rounded-xl p-3 ${active ? 'bg-pine-soft' : ''}`}
                >
                  <Text
                    className={`text-xs font-bold uppercase tracking-wider ${
                      active ? 'text-pine' : 'text-subtle'
                    }`}
                  >
                    {line.speaker}
                  </Text>
                  <Text className={`text-sm leading-6 ${active ? 'text-ink' : 'text-ink/70'}`}>
                    {line.text}
                  </Text>
                </Pressable>
              );
            })}
          </View>
        </ScrollView>
      ) : null}
    </View>
  );
}
