import type { ComponentType } from 'react';
import type { SvgProps } from 'react-native-svg';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Brush,
  Calendar,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Clock,
  CornerDownLeft,
  CornerDownRight,
  Crop,
  Crosshair,
  Download,
  Edit,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  Film,
  Feather,
  File,
  FileDown,
  FilePlus,
  FileText,
  Flame,
  Flag,
  Folder,
  FolderPlus,
  FolderKanban,
  GraduationCap,
  Headphones,
  HelpCircle,
  Highlighter,
  Image,
  Layers,
  Lasso,
  LayoutDashboard,
  Link,
  List,
  Loader,
  LogOut,
  Map,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Monitor,
  MoreHorizontal,
  MousePointer2,
  Network,
  NotebookPen,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Pause,
  PenTool,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquarePen,
  Star,
  Swords,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Volume2,
  VolumeX,
  X,
  XCircle,
  Zap,
  ZoomIn,
} from 'lucide-react-native';

const ICONS = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  award: Award,
  bell: Bell,
  book: Book,
  'book-open': BookOpen,
  bookmark: Bookmark,
  brush: Brush,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  'corner-down-left': CornerDownLeft,
  'corner-down-right': CornerDownRight,
  crop: Crop,
  crosshair: Crosshair,
  download: Download,
  edit: Edit,
  'edit-2': Edit,
  'edit-3': SquarePen,
  eraser: Eraser,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  feather: Feather,
  file: File,
  'file-down': FileDown,
  'file-plus': FilePlus,
  'file-text': FileText,
  flame: Flame,
  flag: Flag,
  folder: Folder,
  'folder-plus': FolderPlus,
  'folder-kanban': FolderKanban,
  'git-merge': Network,
  'graduation-cap': GraduationCap,
  headphones: Headphones,
  'help-circle': HelpCircle,
  highlighter: Highlighter,
  image: Image,
  layers: Layers,
  lasso: Lasso,
  'layout-dashboard': LayoutDashboard,
  'link-2': Link,
  list: List,
  loader: Loader,
  'log-out': LogOut,
  map: Map,
  menu: Menu,
  'message-circle': MessageCircle,
  mic: Mic,
  minus: Minus,
  monitor: Monitor,
  'more-horizontal': MoreHorizontal,
  'mouse-pointer-2': MousePointer2,
  network: Network,
  'notebook-pen': NotebookPen,
  package: Package,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  paperclip: Paperclip,
  pause: Pause,
  'pen-tool': PenTool,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  'refresh-cw': RefreshCw,
  repeat: Repeat2,
  'rotate-ccw': RotateCcw,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  'square-pen': SquarePen,
  star: Star,
  swords: Swords,
  target: Target,
  timer: Timer,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  trophy: Trophy,
  upload: Upload,
  'upload-cloud': UploadCloud,
  user: User,
  'user-check': UserCheck,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  users: Users,
  'users-round': UsersRound,
  film: Film,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
  'zoom-in': ZoomIn,
} satisfies Record<string, ComponentType<SvgProps>>;

export type IconName = keyof typeof ICONS;

/**
 * What an icon is *for*, rather than what colour it happens to be today.
 *
 * Every one of the 236 icons in the app passes an explicit colour, and 213 of
 * those pass a hex literal — because this component takes a plain string, so
 * Tailwind classes cannot reach inside it. That was fine while there was one
 * palette. It stops being fine the moment there are two, since a hex baked into
 * a call site cannot know which one is active.
 *
 * The mapping turned out to be mechanical rather than a matter of taste: those
 * 213 sites use only eleven distinct values, and each maps onto exactly one
 * meaning. So this is a rename with a purpose, not a redesign.
 */
const TONES = {
  /** Body text and most glyphs. */
  muted: '#6F6A5F',
  /** Secondary, de-emphasised. */
  subtle: '#9A9488',
  /** Primary text weight. */
  ink: '#18181B',
  /** On a dark or accent-filled surface. */
  inverse: '#F7F5EE',
  accent: '#B4552D',
  pine: '#2E6F5E',
  amber: '#B4832A',
  rose: '#B0443E',
  /** Dividers and other structural marks. */
  line: '#C9C4B8',
} as const;

export type IconTone = keyof typeof TONES;

export function Icon({
  name,
  size = 16,
  color,
  tone,
  strokeWidth = 1.75,
  ...props
}: SvgProps & {
  name: IconName;
  size?: number;
  /**
   * An explicit colour, for the cases a tone cannot express: subject colours,
   * notebook colours, anything chosen by the student rather than by the theme.
   * Wins over `tone` when both are given.
   */
  color?: string;
  /** Preferred over `color` for anything the theme owns. */
  tone?: IconTone;
  strokeWidth?: number;
}) {
  const Glyph = ICONS[name];
  // Order matters: an explicit colour is always data or brand, and data must
  // never be overridden by a theme.
  const resolved = color ?? (tone ? TONES[tone] : TONES.muted);
  return <Glyph size={size} color={resolved} strokeWidth={strokeWidth} {...props} />;
}
