import type { ComponentType } from 'react';
import type { SvgProps } from 'react-native-svg';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Brush,
  Calendar,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Clock,
  CornerDownLeft,
  CornerDownRight,
  Crop,
  Crosshair,
  Download,
  Edit,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  Film,
  Feather,
  File,
  FileDown,
  FilePlus,
  FileText,
  Flame,
  Flag,
  Folder,
  FolderPlus,
  FolderKanban,
  GraduationCap,
  Headphones,
  HelpCircle,
  Highlighter,
  Image,
  Layers,
  Lasso,
  LayoutDashboard,
  Link,
  List,
  Loader,
  LogOut,
  Map,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Monitor,
  MoreHorizontal,
  MousePointer2,
  Network,
  NotebookPen,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Pause,
  PenTool,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquarePen,
  Star,
  Swords,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Volume2,
  VolumeX,
  X,
  XCircle,
  Zap,
  ZoomIn,
} from 'lucide-react-native';

const ICONS = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  award: Award,
  bell: Bell,
  book: Book,
  'book-open': BookOpen,
  bookmark: Bookmark,
  brush: Brush,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  'corner-down-left': CornerDownLeft,
  'corner-down-right': CornerDownRight,
  crop: Crop,
  crosshair: Crosshair,
  download: Download,
  edit: Edit,
  'edit-2': Edit,
  'edit-3': SquarePen,
  eraser: Eraser,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  feather: Feather,
  file: File,
  'file-down': FileDown,
  'file-plus': FilePlus,
  'file-text': FileText,
  flame: Flame,
  flag: Flag,
  folder: Folder,
  'folder-plus': FolderPlus,
  'folder-kanban': FolderKanban,
  'git-merge': Network,
  'graduation-cap': GraduationCap,
  headphones: Headphones,
  'help-circle': HelpCircle,
  highlighter: Highlighter,
  image: Image,
  layers: Layers,
  lasso: Lasso,
  'layout-dashboard': LayoutDashboard,
  'link-2': Link,
  list: List,
  loader: Loader,
  'log-out': LogOut,
  map: Map,
  menu: Menu,
  'message-circle': MessageCircle,
  mic: Mic,
  minus: Minus,
  monitor: Monitor,
  'more-horizontal': MoreHorizontal,
  'mouse-pointer-2': MousePointer2,
  network: Network,
  'notebook-pen': NotebookPen,
  package: Package,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  paperclip: Paperclip,
  pause: Pause,
  'pen-tool': PenTool,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  'refresh-cw': RefreshCw,
  repeat: Repeat2,
  'rotate-ccw': RotateCcw,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  'square-pen': SquarePen,
  star: Star,
  swords: Swords,
  target: Target,
  timer: Timer,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  trophy: Trophy,
  upload: Upload,
  'upload-cloud': UploadCloud,
  user: User,
  'user-check': UserCheck,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  users: Users,
  'users-round': UsersRound,
  film: Film,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
  'zoom-in': ZoomIn,
} satisfies Record<string, ComponentType<SvgProps>>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 16,
  color = '#1C1917',
  strokeWidth = 1.75,
  ...props
}: SvgProps & {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const Glyph = ICONS[name];
  return <Glyph size={size} color={color} strokeWidth={strokeWidth} {...props} />;
}
