/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2d67f80dde9c22f2b1dd5844c0058479)
interface __BaseEnv_Env {
	DRIVE_TOKENS: KVNamespace;
	MATERIALS: R2Bucket;
	R2_BUCKET: "notomi-materials";
	FIREBASE_PROJECT_ID: "notomii";
	ALLOWED_ORIGINS: "https://notomii.web.app,https://notomii.firebaseapp.com,http://localhost:8081";
	GOOGLE_CLIENT_ID: "666272925159-qkidb4n2nv4a376qksdnt6vjk4dne6ih.apps.googleusercontent.com";
	REMINDER_DEVICES: DurableObjectNamespace<import("./src/index").ReminderDevice>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ReminderDevice";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_BUCKET" | "FIREBASE_PROJECT_ID" | "ALLOWED_ORIGINS" | "GOOGLE_CLIENT_ID">> {}
}
