/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 494e2969185aaa9185777e8676b10e58)
interface __BaseEnv_Env {
	MATERIALS: R2Bucket;
	R2_BUCKET: "notomi-materials";
	FIREBASE_PROJECT_ID: "notomii";
	ALLOWED_ORIGINS: "https://notomii.web.app,https://notomii.firebaseapp.com,http://localhost:8081";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_BUCKET" | "FIREBASE_PROJECT_ID" | "ALLOWED_ORIGINS">> {}
}
